# Generated by Django 6.0.2 on 2026-04-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0003_alter_product_options_alter_sellerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='balance'),
        ),
    ]
