# Generated by Django 6.0.2 on 2026-04-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0004_alter_customerprofile_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='balance',
            field=models.FloatField(default=0.0, verbose_name='balance'),
        ),
    ]
