# Generated by Django 6.0.2 on 2026-04-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0006_alter_customerprofile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='stock'),
        ),
    ]
