# Generated by Django 6.0.2 on 2026-04-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0007_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='balance'),
        ),
    ]
