# Generated by Django 6.0.2 on 2026-04-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0008_sellerprofile_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(editable=False, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='description'),
        ),
    ]
