# Generated by Django 6.0.2 on 2026-04-20 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0010_category_alter_order_options_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='onlineshop.category', verbose_name='category'),
            preserve_default=False,
        ),
    ]
